name: Deploy Docker App (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Stop & Remove Existing Container
      run: |
        docker stop myapp || true
        docker rm myapp || true

    - name: Build Docker Image
      run: docker build -t myapp .

    - name: Run Docker Container
      run: docker run -d -p 80:80 --name myapp myapp
