name: Deploy Docker App (Self-Hosted to Remote Docker VM)

on:
  push:
    branches:
      - main

jobs:
  cicd:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Remote Docker VM
      env:
        DOCKER_HOST: ${{ secrets.DOCKER_VM_HOST }}   # e.g. ubuntu@172.31.30.71
        SSH_KEY: ${{ secrets.DOCKER_VM_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem

        # Create app folder on remote VM
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem $DOCKER_HOST "mkdir -p ~/myapp"

        # Copy files to remote VM
        rsync -avz -e "ssh -i ssh_key.pem -o StrictHostKeyChecking=no" ./ $DOCKER_HOST:~/myapp

        # Build & run container remotely
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem $DOCKER_HOST << 'EOF'
          cd ~/myapp
          docker stop myapp || true
          docker rm myapp || true
          docker build -t myapp .
          docker run -d -p 80:80 --name myapp myapp
        EOF
